package br.com.system.model;

// Generated 01/11/2007 10:45:33 by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Logica generated by hbm2java
 */
@Entity
@Table(name = "logica")
public class Logica extends Base  implements java.io.Serializable {

	private String path;

	public Logica() {
	}


	@Column(name = "path", length = 20)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}


}
