/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-11-29 15:15:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hospedagem;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detalhes_ok_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("jar:file:/C:/temp/workspace/NetLab/webContent/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098721890000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1659649837984L));
    _jspx_dependants.put("jar:file:/C:/temp/workspace/NetLab/webContent/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098721890000L));
    _jspx_dependants.put("/WEB-INF/lib/displaytag-1.1.jar", Long.valueOf(1659649835858L));
    _jspx_dependants.put("jar:file:/C:/temp/workspace/NetLab/webContent/WEB-INF/lib/displaytag-1.1.jar!/META-INF/displaytag.tld", Long.valueOf(1139771322000L));
    _jspx_dependants.put("/hospedagem/../template/cabecalhomodal.jsp", Long.valueOf(1661614491429L));
    _jspx_dependants.put("jar:file:/C:/temp/workspace/NetLab/webContent/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098721890000L));
    _jspx_dependants.put("/template/tags.jsp", Long.valueOf(1660135498822L));
    _jspx_dependants.put("/template/head.jsp", Long.valueOf(1666625609587L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html class=\"no-js\" lang=\"\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n");
      out.write("<title>NetLab - Administração</title>\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<!-- normalize -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/normalize.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- favicon\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\"\n");
      out.write("	href=\"http://www.sistemanetlab.com.br/site/imagens/favicon.png\">\n");
      out.write("<!-- Google Fonts\n");
      out.write("		============================================ -->\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<!-- Bootstrap CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- load css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/load.css\">\n");
      out.write("\n");
      out.write("<!-- media css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/media.css\">\n");
      out.write("\n");
      out.write("<!-- font awesome CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/font-awesome.min.css\">\n");
      out.write("<!-- owl.carousel CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/owl.carousel.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/owl.theme.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/owl.transitions.css\">\n");
      out.write("<!-- meanmenu CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/meanmenu/meanmenu.min.css\">\n");
      out.write("<!-- animate CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/animate.css\">\n");
      out.write("<!-- summernote CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/summernote/summernote.css\">\n");
      out.write("<!-- Range Slider CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/themesaller-forms.css\">\n");
      out.write("<!-- normalize CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/normalize.css\">\n");
      out.write("<!-- mCustomScrollbar CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"template/css/scrollbar/jquery.mCustomScrollbar.min.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- jvectormap CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"template/css/jvectormap/jquery-jvectormap-2.0.3.css\">\n");
      out.write("\n");
      out.write("<!-- Notika icon CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/notika-custom-icon.css\">\n");
      out.write("<!-- bootstrap select CSS\n");
      out.write("		============================================ -->\n");
      out.write("\n");
      out.write("<!-- datapicker CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/datapicker/datepicker3.css\">\n");
      out.write("<!-- Color Picker CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/color-picker/farbtastic.css\">\n");
      out.write("<!-- main CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/chosen/chosen.css\">\n");
      out.write("<!-- notification CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/notification/notification.css\">\n");
      out.write("<!-- dropzone CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/dropzone/dropzone.css\">\n");
      out.write("<!-- wave CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/wave/waves.min.css\">\n");
      out.write("\n");
      out.write("<!-- dialog CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/dialog/sweetalert2.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/dialog/dialog.css\">\n");
      out.write("\n");
      out.write("<!-- main CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/main.css\">\n");
      out.write("<!-- style CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/style.css?xx\">\n");
      out.write("<!-- responsive CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/responsive.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Data Table JS\n");
      out.write("        ============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/jquery.dataTables.min.css\">\n");
      out.write("<!-- update \n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/DataTables/datatables.css\">-->\n");
      out.write(" \n");
      out.write("  \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- modernizr JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/vendor/modernizr-2.8.3.min.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"https://kit.fontawesome.com/729fc1114d.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Data Table area Start-->\r\n");
      out.write("\r\n");
      out.write("<div class=\"panel panel-collapse notika-accrodion-cus\">\r\n");
      out.write("	<div class=\"panel-heading\" role=\"tab\">\r\n");
      out.write("		<h4 class=\"panel-title\">\r\n");
      out.write("			<a data-toggle=\"collapse\" data-parent=\"#accordionGreen\"\r\n");
      out.write("				href=\"#accordionGreen-one\" aria-expanded=\"false\" class=\"collapsed\"\r\n");
      out.write("				id=\"credetial-BD\">Credenciais do Banco</a>\r\n");
      out.write("		</h4>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"accordionGreen-one\" class=\"collapse\" role=\"tabpanel\"\r\n");
      out.write("		aria-expanded=\"false\" style=\"height: 0px;\">\r\n");
      out.write("		<div class=\"panel-body\" id=\"content-credential-BD\">\r\n");
      out.write("			<div class=\"form-example-int form-horizental\">\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("							<label class=\"hrzn-fm\">User Name:</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("							<div class=\"nk-int-st\">\r\n");
      out.write("								<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.userBd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-example-int form-horizental\">\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("							<label class=\"hrzn-fm\">Password:</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("							<div class=\"nk-int-st\">\r\n");
      out.write("								<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.senhaBd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-example-int form-horizental\">\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("							<label class=\"hrzn-fm\">URL:</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("							<div class=\"nk-int-st\">\r\n");
      out.write("								<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.hostBd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"panel panel-collapse notika-accrodion-cus\">\r\n");
      out.write("	<div class=\"panel-heading\" role=\"tab\">\r\n");
      out.write("		<h4 class=\"panel-title\">\r\n");
      out.write("			<a class=\"collapsed\" data-toggle=\"collapse\"\r\n");
      out.write("				data-parent=\"#accordionGreen\" href=\"#accordionGreen-two\"\r\n");
      out.write("				aria-expanded=\"false\" id=\"credential-FTP\"> Credenciais do FTP </a>\r\n");
      out.write("		</h4>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"accordionGreen-two\" class=\"collapse\" role=\"tabpanel\"\r\n");
      out.write("		aria-expanded=\"false\" style=\"height: 0px;\">\r\n");
      out.write("		<div class=\"panel-body\" id=\"content-credetial-FTP\">\r\n");
      out.write("			<div class=\"form-example-int form-horizental\">\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("							<label class=\"hrzn-fm\">Host FTP:</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("							<div class=\"nk-int-st\">\r\n");
      out.write("								<label><a href=\"ftp://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.hostFtp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.hostFtp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a></label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-example-int form-horizental\">\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("							<label class=\"hrzn-fm\">User FTP:</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("							<div class=\"nk-int-st\">\r\n");
      out.write("								<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.userFtp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-example-int form-horizental\">\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("							<label class=\"hrzn-fm\">Password FTP:</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("							<div class=\"nk-int-st\">\r\n");
      out.write("								<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.senhaFtp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- ------- -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"panel panel-collapse notika-accrodion-cus\">\r\n");
      out.write("	<div class=\"panel-heading\" role=\"tab\">\r\n");
      out.write("		<h4 class=\"panel-title\">\r\n");
      out.write("			<a class=\"collapsed\" data-toggle=\"collapse\"\r\n");
      out.write("				data-parent=\"#accordionGreen\" href=\"#accordionGreen-pobre\"\r\n");
      out.write("				aria-expanded=\"false\" id=\"credential-probe\"> Credenciais do\r\n");
      out.write("				Probe </a>\r\n");
      out.write("		</h4>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"accordionGreen-pobre\" class=\"collapse\" role=\"tabpanel\"\r\n");
      out.write("		aria-expanded=\"false\" style=\"height: 0px;\">\r\n");
      out.write("		<div class=\"panel-body\" id=\"content-credetial-probe\">\r\n");
      out.write("			<div class=\"form-example-int form-horizental\">\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("							<label class=\"hrzn-fm\">Username:</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("							<div class=\"nk-int-st\">\r\n");
      out.write("								<label>netlab</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-example-int form-horizental\">\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("							<label class=\"hrzn-fm\">Password:</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("							<div class=\"nk-int-st\">\r\n");
      out.write("								<label>25Ymrmf13#</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-example-int form-horizental\">\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("							<label class=\"hrzn-fm\">Pobre3:</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("							<div class=\"nk-int-st\">\r\n");
      out.write("								<a href=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.dominioPrincipal}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/probe3/logs/download?logType=log4j&webapp=%2flis&root=true&logIndex=file\">Acessar</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ---- -->\r\n");
      out.write("<div class=\"panel panel-collapse notika-accrodion-cus\">\r\n");
      out.write("	<div class=\"panel-heading\" role=\"tab\">\r\n");
      out.write("		<h4 class=\"panel-title\">\r\n");
      out.write("			<a class=\"collapsed\" data-toggle=\"collapse\"\r\n");
      out.write("				data-parent=\"#accordionGreen\" href=\"#accordionGreen-three\"\r\n");
      out.write("				aria-expanded=\"false\" id=\"credetial-details\"> Detalhes </a>\r\n");
      out.write("		</h4>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"accordionGreen-three\" class=\"collapse\" role=\"tabpanel\"\r\n");
      out.write("		aria-expanded=\"false\" style=\"height: 0px;\">\r\n");
      out.write("		<div class=\"panel-body\" id=\"content-credential-details\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<!-- content Credential Details -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"data-table-area\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("							<div class=\"data-table-list\">\r\n");
      out.write("								<div class=\"basic-tb-hd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12 tabhead\">\r\n");
      out.write("													<label class=\"hrzn-fm \">Contrato:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.tipoContrato}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Domínio Secundário:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.dominioSecundario}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Mensalidade:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Nome Contato:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.nomeContato}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Telefone Contato:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.telefoneContato}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Descrição:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.descricao}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Cadastrado em:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Modificado em:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      if (_jspx_meth_fmt_005fformatDate_005f1(_jspx_page_context))
        return;
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Status:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-10 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<label> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Id Usuário Criador:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.idUsuarioCriador}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Id Usuário Modificador:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.idUsuarioModificador}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Data Adesão:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.dataAdesao}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Mês Renovação:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.mesRenovacao}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Faturamento:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.tipoMensalidade}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Cidade:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.cidade}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Versão:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.versao}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Laboratório:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.nomeLab}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">CNPJ:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.cnpj}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">CNES:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.cnes}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">E-mail:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Instagram:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.insta}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">IP:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.ip}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Senha FTP:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.senhaFtp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Senha BD:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.senhaBd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-example-int form-horizental\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"row\">\r\n");
      out.write("												<div class=\"col-lg-2 col-md-3 col-sm-3 col-xs-12\">\r\n");
      out.write("													<label class=\"hrzn-fm\">Capacidade DB:</label>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("													<div class=\"nk-int-st\">\r\n");
      out.write("														<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.capacidadeBd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"table-responsive\">\r\n");
      out.write("									<span id=\"displaytag_lista\"></span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<!-- end data-table-list -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Data Table area End-->\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
      // /hospedagem/detalhes.ok.jsp(247,21) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,##0.00");
      // /hospedagem/detalhes.ok.jsp(247,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.mensalidade}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /hospedagem/detalhes.ok.jsp(304,21) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("dd/MM/yyyy HH:mm");
      // /hospedagem/detalhes.ok.jsp(304,21) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.dataCriacao}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f1.setParent(null);
      // /hospedagem/detalhes.ok.jsp(320,21) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setPattern("dd/MM/yyyy HH:mm");
      // /hospedagem/detalhes.ok.jsp(320,21) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.dataModificacao}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
      _jspx_th_fmt_005fformatDate_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f1_reused);
    }
    return false;
  }
}
