/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2023-01-12 13:12:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hospedagem;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import br.com.system.bo.*;
import br.com.system.dao.*;
import br.com.system.model.*;
import java.util.ArrayList;
import java.util.List;

public final class resultset_ok_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(12);
    _jspx_dependants.put("/hospedagem/../template/rodapefinal.jsp", Long.valueOf(1661614718354L));
    _jspx_dependants.put("jar:file:/C:/temp/workspace/NetLab/webContent/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098721890000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1659649837984L));
    _jspx_dependants.put("jar:file:/C:/temp/workspace/NetLab/webContent/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098721890000L));
    _jspx_dependants.put("/WEB-INF/lib/displaytag-1.1.jar", Long.valueOf(1659649835858L));
    _jspx_dependants.put("jar:file:/C:/temp/workspace/NetLab/webContent/WEB-INF/lib/displaytag-1.1.jar!/META-INF/displaytag.tld", Long.valueOf(1139771322000L));
    _jspx_dependants.put("/hospedagem/../template/cabecalho.jsp", Long.valueOf(1668121643145L));
    _jspx_dependants.put("jar:file:/C:/temp/workspace/NetLab/webContent/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098721890000L));
    _jspx_dependants.put("/template/menu.jsp", Long.valueOf(1673017524707L));
    _jspx_dependants.put("/template/tags.jsp", Long.valueOf(1660135498822L));
    _jspx_dependants.put("/template/head.jsp", Long.valueOf(1666625609587L));
    _jspx_dependants.put("/hospedagem/../template/rodapejs.jsp", Long.valueOf(1661787364034L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("br.com.system.bo");
    _jspx_imports_packages.add("br.com.system.dao");
    _jspx_imports_packages.add("br.com.system.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html class=\"no-js\" lang=\"\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n");
      out.write("<title>NetLab - Administração</title>\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<!-- normalize -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/normalize.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- favicon\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\"\n");
      out.write("	href=\"http://www.sistemanetlab.com.br/site/imagens/favicon.png\">\n");
      out.write("<!-- Google Fonts\n");
      out.write("		============================================ -->\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<!-- Bootstrap CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- load css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/load.css\">\n");
      out.write("\n");
      out.write("<!-- media css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/media.css\">\n");
      out.write("\n");
      out.write("<!-- font awesome CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/font-awesome.min.css\">\n");
      out.write("<!-- owl.carousel CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/owl.carousel.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/owl.theme.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/owl.transitions.css\">\n");
      out.write("<!-- meanmenu CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/meanmenu/meanmenu.min.css\">\n");
      out.write("<!-- animate CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/animate.css\">\n");
      out.write("<!-- summernote CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/summernote/summernote.css\">\n");
      out.write("<!-- Range Slider CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/themesaller-forms.css\">\n");
      out.write("<!-- normalize CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/normalize.css\">\n");
      out.write("<!-- mCustomScrollbar CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"template/css/scrollbar/jquery.mCustomScrollbar.min.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- jvectormap CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"template/css/jvectormap/jquery-jvectormap-2.0.3.css\">\n");
      out.write("\n");
      out.write("<!-- Notika icon CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/notika-custom-icon.css\">\n");
      out.write("<!-- bootstrap select CSS\n");
      out.write("		============================================ -->\n");
      out.write("\n");
      out.write("<!-- datapicker CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/datapicker/datepicker3.css\">\n");
      out.write("<!-- Color Picker CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/color-picker/farbtastic.css\">\n");
      out.write("<!-- main CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/chosen/chosen.css\">\n");
      out.write("<!-- notification CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/notification/notification.css\">\n");
      out.write("<!-- dropzone CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/dropzone/dropzone.css\">\n");
      out.write("<!-- wave CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/wave/waves.min.css\">\n");
      out.write("\n");
      out.write("<!-- dialog CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/dialog/sweetalert2.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/dialog/dialog.css\">\n");
      out.write("\n");
      out.write("<!-- main CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/main.css\">\n");
      out.write("<!-- style CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/style.css?xx\">\n");
      out.write("<!-- responsive CSS\n");
      out.write("		============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/responsive.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Data Table JS\n");
      out.write("        ============================================ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"template/css/jquery.dataTables.min.css\">\n");
      out.write("<!-- update \n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/DataTables/datatables.css\">-->\n");
      out.write(" \n");
      out.write("  \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- modernizr JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/vendor/modernizr-2.8.3.min.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"https://kit.fontawesome.com/729fc1114d.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("	<!--[if lt IE 8]>\n");
      out.write("            <p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"http://browsehappy.com/\">upgrade your browser</a> to improve your experience.</p>\n");
      out.write("        <![endif]-->\n");
      out.write("	<!-- Start Header Top Area -->\n");
      out.write("	<div class=\"header-top-area\">\n");
      out.write("		<div class=\"container2\">\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-lg-4 col-md-4 col-sm-12 col-xs-12\">\n");
      out.write("					<div class=\"logo-area\">\n");
      out.write("						<a href=\"main.home.logic\"><font size=\"4\" color=\"#FFFFFF\"><strong><font\n");
      out.write("									size=\"6\" face=\"Verdana, Arial, Helvetica, sans-serif\"\n");
      out.write("									color=\"#FF6600\">::</font><font size=\"6\"\n");
      out.write("									face=\"Verdana, Arial, Helvetica, sans-serif\" color=\"#FFFFFF\">Net</font><font\n");
      out.write("									size=\"6\" face=\"Verdana, Arial, Helvetica, sans-serif\"\n");
      out.write("									color=\"#FF6600\">Lab</font><font size=\"6\" color=\"#FFFFFF\">::</font></strong></font>\n");
      out.write("						</a>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<!--  -->\n");
      out.write("\n");
      out.write("				<!--  -->\n");
      out.write("\n");
      out.write("				<!--  -->\n");
      out.write("				<div class=\"col-lg-8 col-md-8 col-sm-12 col-xs-12\">\n");
      out.write("					<div class=\"header-top-menu\">\n");
      out.write("						<ul class=\"nav navbar-nav notika-top-nav\">\n");
      out.write("							<li class=\"nav-item\"><div class=\"dropdown-trig-sgn\"\n");
      out.write("									id=\"usuarioSessao\">\n");
      out.write("									<a class=\" triger-fadeIn waves-effect\" data-toggle=\"dropdown\"\n");
      out.write("										aria-expanded=\"false\" id=\"perfil\"><span><i\n");
      out.write("											class=\"glyphicon glyphicon-user\"></i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.logado.descricao}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("										<span><i class=\"glyphicon glyphicon-chevron-down\"></i></span>\n");
      out.write("									</a>\n");
      out.write("									<ul class=\"dropdown-menu triger-fadeIn-dp animated fadeIn\">\n");
      out.write("										<li><a href=\"admin.logout.logic\">Logout</a></li>\n");
      out.write("\n");
      out.write("									</ul>\n");
      out.write("								</div>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<!-- - -->\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- End Header Top Area -->\n");
      out.write("\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Mobile Menu start -->\r\n");
      out.write("<div class=\"mobile-menu-area\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("				<div class=\"mobile-menu\">\r\n");
      out.write("					<nav id=\"dropdown\">\r\n");
      out.write("						<ul class=\"mobile-menu-nav\">\r\n");
      out.write("							<li><a data-toggle=\"collapse\" data-target=\"#Charts\"\r\n");
      out.write("								href=\"main.home.logic\">Home</a></li>\r\n");
      out.write("							<li><a data-toggle=\"collapse\" data-target=\"#demoevent\"\r\n");
      out.write("								href=\"#\">Cadastros</a>\r\n");
      out.write("								<ul id=\"demoevent\" class=\"collapse dropdown-header-top\">\r\n");
      out.write("									<li><a href=\"configuracao.listar.logic\">Configuração</a></li>\r\n");
      out.write("									<li><a href=\"hospedagem.listar.logic\">Hospedagem</a></li>\r\n");
      out.write("									<li><a href=\"hospedagem.listar.logic?hospedagem.destino=1\">Imagens</a></li>\r\n");
      out.write("									<li><a href=\"admin.lista.logic\">Usuário</a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li><a data-toggle=\"collapse\" data-target=\"#event\" href=\"#\">Consulta\r\n");
      out.write("									SQL</a>\r\n");
      out.write("								<ul id=\"event\" class=\"collapse dropdown-header-top\">\r\n");
      out.write("									<li><a href=\"hospedagem.buscacomponente.logic\">Componentes</a></li>\r\n");
      out.write("									<li><a href=\"hospedagem.resultset.logic\">Result Set</a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li><a data-toggle=\"collapse\" data-target=\"#links\" href=\"#\">Links</a>\r\n");
      out.write("								<ul id=\"event\" class=\"collapse dropdown-header-top\">\r\n");
      out.write("									<li><a\r\n");
      out.write("										href=\"https://gde.diagnosticosdobrasil.com.br/GDE_Home/\">DB</a></li>\r\n");
      out.write("									<li><a href=\"https://aol.alvaroapoio.com.br/exames/\">Álvaro</a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li><a data-toggle=\"collapse\" data-target=\"#Charts\"\r\n");
      out.write("								href=\"admin.logout.logic\">Logout</a></li>\r\n");
      out.write("\r\n");
      out.write("						</ul>\r\n");
      out.write("					</nav>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Mobile Menu end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Main Menu area start-->\r\n");
      out.write("<div class=\"main-menu-area mg-t-10\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\"\r\n");
      out.write("				style=\"margin-left: -1.5em;\">\r\n");
      out.write("				<ul class=\"nav nav-tabs notika-menu-wrap menu-it-icon-pro\">\r\n");
      out.write("					<li class=\"\"><a href=\"main.home.logic\"><i\r\n");
      out.write("							class=\"notika-icon notika-house\"></i> Home</a></li>\r\n");
      out.write("					<li class=\"\"><a data-toggle=\"tab\" href=\"#cadastros\"\r\n");
      out.write("						aria-expanded=\"false\"><i class=\"notika-icon notika-form\"></i>\r\n");
      out.write("							Cadastros</a></li>\r\n");
      out.write("					<li class=\"\"><a data-toggle=\"tab\" href=\"#consultaSQL\"\r\n");
      out.write("						aria-expanded=\"false\"><i class=\"notika-icon notika-edit\"></i>\r\n");
      out.write("							Consultas SQL</a></li>\r\n");
      out.write("					<li class=\"\"><a data-toggle=\"tab\" href=\"#Links\"\r\n");
      out.write("						aria-expanded=\"false\"><i class=\"glyphicon glyphicon-link\"></i>\r\n");
      out.write("							Links</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<!-- content cadastro -->\r\n");
      out.write("				<div class=\"tab-content custom-menu-content\">\r\n");
      out.write("					<div id=\"cadastros\"\r\n");
      out.write("						class=\"tab-pane in notika-tab-menu-bg animated flipInX\">\r\n");
      out.write("						<ul class=\"notika-main-menu-dropdown\">\r\n");
      out.write("							<li class=\"nav-drop\"><a href=\"configuracao.listar.logic\">Configuração</a></li>\r\n");
      out.write("							<li class=\"nav-drop\"><a href=\"hospedagem.listar.logic\">Hospedagem</a></li>\r\n");
      out.write("							<li class=\"nav-drop\"><a\r\n");
      out.write("								href=\"hospedagem.listar.logic?hospedagem.destino=1\">Imagens</a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li class=\"nav-drop\"><a href=\"admin.lista.logic\">Usuários</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"consultaSQL\"\r\n");
      out.write("						class=\"tab-pane in notika-tab-menu-bg animated flipInX\">\r\n");
      out.write("						<ul class=\"notika-main-menu-dropdown\">\r\n");
      out.write("							<li class=\"nav-drop\"><a\r\n");
      out.write("								href=\"hospedagem.buscacomponente.logic\">Componentes</a></li>\r\n");
      out.write("							<li class=\"nav-drop\"><a href=\"hospedagem.resultset.logic\">Result\r\n");
      out.write("									SET</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"Links\"\r\n");
      out.write("						class=\"tab-pane in notika-tab-menu-bg animated flipInX\">\r\n");
      out.write("						<ul class=\"notika-main-menu-dropdown\">\r\n");
      out.write("							<li class=\"nav-drop\"><a\r\n");
      out.write("								href=\"https://gde.diagnosticosdobrasil.com.br/GDE_Home/\">DB</a></li>\r\n");
      out.write("							<li class=\"nav-drop\"><a href=\"https://aol.alvaroapoio.com.br/exames/\">Álvaro</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Main Menu area End-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Object obj=(Object)session.getAttribute("listaResultSet");
ArrayList<ResultSet> lista = null;
if(obj!=null)
	lista=(ArrayList<ResultSet>)obj;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"hospedagem.resultSQL.logic\" method=\"post\" class=\"\">\r\n");
      out.write("	<div class=\"container-resultset\">\r\n");
      out.write("		<div class=\"col-lg-3 col-md-7 col-sm-7 col-xs-12\">\r\n");
      out.write("			<div class=\"nk-int-st\">\r\n");
      out.write("				<label class=\"hrzn-fm\">ResultSet:</label>\r\n");
      out.write("				<textarea rows=\"5\" cols=\"130\" \r\n");
      out.write("					name=\"hospedagem.resultset\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hospedagem.resultset}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("			</div>\r\n");
      out.write("			<button style=\"margin-left: 1em;\" type=\"submit\"\r\n");
      out.write("			class=\"btn btn-success notika-btn-success waves-effect\">Pesquisar</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 if(lista!=null){ 
      out.write("\r\n");
      out.write("		<table id=\"item1\" cellpadding=\"1\" class=\"table table-striped table-hover table-condensed table-bordered\" cellspacing=\"2\">\r\n");
      out.write("		<thead>\r\n");
      out.write("		<tr>\r\n");
      out.write("	");
boolean theadOk=false;

	for (ResultSet rs : lista) {
		ResultSetMetaData metaData = rs.getMetaData();
		int numeroDeColunas = metaData.getColumnCount();
		/*if(!theadOk){*/
	    for (int coluna = 1; coluna <= numeroDeColunas; coluna++) { 
      out.write("\r\n");
      out.write("	        <th class=\"sorted order2\">");
      out.print(metaData.getColumnName(coluna));
      out.write("</th>\r\n");
      out.write("	    ");
}
      out.write("\r\n");
      out.write("         </tr></thead><tbody>\r\n");
      out.write("         ");
/* theadOk=true; }*/
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         \r\n");
      out.write("        ");
rs.beforeFirst(); while (rs.next()) { 
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("        ");

	            for (int coluna = 1; coluna <= numeroDeColunas; coluna++) { 
      out.write("\r\n");
      out.write("	                \r\n");
      out.write("	                <td class=\"sorted order2\">");
      out.print(rs.getObject(coluna));
      out.write("</td>\r\n");
      out.write("	            ");
}
      out.write("\r\n");
      out.write("	            \r\n");
      out.write("	        ");
}
      out.write("\r\n");
      out.write("         </tr>\r\n");
      out.write("         \r\n");
      out.write("	");
}
      out.write("\r\n");
      out.write("	</tbody></table>\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<!-- end conteinet2-->\n");
      out.write("\n");
      out.write("<!-- Start Footer area-->\n");
      out.write("<div class=\"footer-copyright-area1\">\n");
      out.write("	<div>\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\">\n");
      out.write("				<div class=\"footer-copy-right\">\n");
      out.write("					<p>\n");
      out.write("						Copyright Â© 2012. Todos os direitos reservados. Template by <a\n");
      out.write("							href=\"https://colorlib.com\">Colorlib</a>.\n");
      out.write("					</p>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("<!-- End Footer area-->\n");
      out.write("<!-- jquery\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/vendor/jquery-1.12.4.min.js\"></script>\n");
      out.write("<!-- bootstrap JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/bootstrap.min.js\"></script>\n");
      out.write("<!-- wow JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/wow.min.js\"></script>\n");
      out.write("<!-- price-slider JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/jquery-price-slider.js\"></script>\n");
      out.write("<!-- owl.carousel JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/owl.carousel.min.js\"></script>\n");
      out.write("<!-- scrollUp JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/jquery.scrollUp.min.js\"></script>\n");
      out.write("<!-- meanmenu JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/meanmenu/jquery.meanmenu.js\"></script>\n");
      out.write("<!-- counterup JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/counterup/jquery.counterup.min.js\"></script>\n");
      out.write("<script src=\"template/js/counterup/waypoints.min.js\"></script>\n");
      out.write("<script src=\"template/js/counterup/counterup-active.js\"></script>\n");
      out.write("<!-- mCustomScrollbar JS\n");
      out.write("		============================================ -->\n");
      out.write("<script\n");
      out.write("	src=\"template/js/scrollbar/jquery.mCustomScrollbar.concat.min.js\"></script>\n");
      out.write("<!-- sparkline JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/sparkline/jquery.sparkline.min.js\"></script>\n");
      out.write("<script src=\"template/js/sparkline/sparkline-active.js\"></script>\n");
      out.write("<!-- flot JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/flot/jquery.flot.js\"></script>\n");
      out.write("<script src=\"template/js/flot/jquery.flot.resize.js\"></script>\n");
      out.write("<script src=\"template/js/flot/curvedLines.js\"></script>\n");
      out.write("<script src=\"template/js/flot/flot-active.js\"></script>\n");
      out.write("<!-- knob JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/knob/jquery.knob.js\"></script>\n");
      out.write("<script src=\"template/js/knob/jquery.appear.js\"></script>\n");
      out.write("<script src=\"template/js/knob/knob-active.js\"></script>\n");
      out.write("<!-- Input Mask JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/jasny-bootstrap.min.js\"></script>\n");
      out.write("<!-- icheck JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/icheck/icheck.min.js\"></script>\n");
      out.write("<script src=\"template/js/icheck/icheck-active.js\"></script>\n");
      out.write("<!-- rangle-slider JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/rangle-slider/jquery-ui-1.10.4.custom.min.js\"></script>\n");
      out.write("<script src=\"template/js/rangle-slider/jquery-ui-touch-punch.min.js\"></script>\n");
      out.write("<script src=\"template/js/rangle-slider/rangle-active.js\"></script>\n");
      out.write("<!-- datapicker JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/datapicker/bootstrap-datepicker.js\"></script>\n");
      out.write("<script src=\"template/js/datapicker/datepicker-active.js\"></script>\n");
      out.write("<!-- bootstrap select JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/bootstrap-select/bootstrap-select.js\"></script>\n");
      out.write("<!--  color-picker JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/color-picker/farbtastic.min.js\"></script>\n");
      out.write("<script src=\"template/js/color-picker/color-picker.js\"></script>\n");
      out.write("<!--  notification JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/notification/bootstrap-growl.min.js\"></script>\n");
      out.write("<script src=\"template/js/notification/notification-active.js\"></script>\n");
      out.write("<!--  summernote JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/summernote/summernote-updated.min.js\"></script>\n");
      out.write("<script src=\"template/js/summernote/summernote-active.js\"></script>\n");
      out.write("<!-- dropzone JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/dropzone/dropzone.js\"></script>\n");
      out.write("<!--  wave JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/wave/waves.min.js\"></script>\n");
      out.write("<script src=\"template/js/wave/wave-active.js\"></script>\n");
      out.write("<!--  chosen JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/chosen/chosen.jquery.js\"></script>\n");
      out.write("<!--  Chat JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/chat/jquery.chat.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"template/js/dialog/sweetalert2.min.js\"></script>\n");
      out.write("<script src=\"template/js/dialog/dialog-active.js\"></script>\n");
      out.write("\n");
      out.write("<!--  todo JS ============================================ -->\n");
      out.write("\n");
      out.write("<script src=\"template/js/todo/jquery.todo.js\"></script>\n");
      out.write("<!-- plugins JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/plugins.js\"></script>\n");
      out.write("<!-- main JS\n");
      out.write("		============================================ -->\n");
      out.write("<script src=\"template/js/main.js\"></script>\n");
      out.write("<!-- tawk chat JS\n");
      out.write("		============================================ -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Data Table JS\n");
      out.write("        ============================================ -->\n");
      out.write("<script src=\"template/js/data-table/jquery.dataTables.min.js\"></script>\n");
      out.write("<script src=\"template/js/data-table/data-table-act.js\"></script>\n");
      out.write("<script src=\"admin.sistemanetlab.med.br_netlab_template_js_data-table_jquery.dataTables.min.js\"></script>\n");
      out.write("<!--  update \n");
      out.write("<script type=\"text/javascript\" charset=\"utf8\" src=\"https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js\"></script>\n");
      out.write("<script type=\"text/javascript\" charset=\"utf8\" src=\"/DataTables/datatables.js\"></script>-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- jvectormap JS\n");
      out.write("        ============================================ -->\n");
      out.write("<script src=\"template/js/jvectormap/jquery-jvectormap-2.0.2.min.js\"></script>\n");
      out.write("<script src=\"template/js/jvectormap/jquery-jvectormap-world-mill-en.js\"></script>\n");
      out.write("<script src=\"template/js/jvectormap/jvectormap-active.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	$(document)\r\n");
      out.write("			.ready(\r\n");
      out.write("					function() {\r\n");
      out.write("\r\n");
      out.write("						$(window)\r\n");
      out.write("								.load(\r\n");
      out.write("										function() {\r\n");
      out.write("											$(\".laboratorio\")\r\n");
      out.write("													.each(\r\n");
      out.write("															function(index) {\r\n");
      out.write("																var contexto = $(\r\n");
      out.write("																		this)\r\n");
      out.write("																		.attr(\r\n");
      out.write("																				\"data-contexto\");\r\n");
      out.write("																var urlContexto = \"http://\"\r\n");
      out.write("																		+ contexto\r\n");
      out.write("																		+ \".sistemanetlab.med.br/lis/dados.jsp\";\r\n");
      out.write("																var urlServidor = \"http://\"\r\n");
      out.write("																		+ contexto\r\n");
      out.write("																		+ \".sistemanetlab.med.br/index.jsp\";\r\n");
      out.write("																var laboratorio = $(this);\r\n");
      out.write("\r\n");
      out.write("																$\r\n");
      out.write("																		.ajax(\r\n");
      out.write("																				{\r\n");
      out.write("																					url : urlContexto,\r\n");
      out.write("																					method : 'get',\r\n");
      out.write("\r\n");
      out.write("																				})\r\n");
      out.write("																		.done(\r\n");
      out.write("																				function(\r\n");
      out.write("																						data) {\r\n");
      out.write("																					if ($\r\n");
      out.write("																							.isEmptyObject(data) == false) {\r\n");
      out.write("																						laboratorio\r\n");
      out.write("																								.addClass(\"glyphicon glyphicon-ok\");\r\n");
      out.write("																						$(\r\n");
      out.write("																								\".c-loader\")\r\n");
      out.write("																								.removeClass(\r\n");
      out.write("																										\"c-loader\");\r\n");
      out.write("\r\n");
      out.write("																					}\r\n");
      out.write("																				})\r\n");
      out.write("																		.fail(\r\n");
      out.write("																				function() {\r\n");
      out.write("																					laboratorio\r\n");
      out.write("																							.addClass(\"glyphicon glyphicon-alert\");\r\n");
      out.write("																					$(\r\n");
      out.write("																							\".c-loader\")\r\n");
      out.write("																							.removeClass(\r\n");
      out.write("																									\"c-loader\");\r\n");
      out.write("																				})\r\n");
      out.write("\r\n");
      out.write("															})\r\n");
      out.write("\r\n");
      out.write("											$(\"input\").focus();\r\n");
      out.write("\r\n");
      out.write("										});\r\n");
      out.write("\r\n");
      out.write("						$('.tabela').hover(function() {\r\n");
      out.write("							$(\"input\").focus();\r\n");
      out.write("						});\r\n");
      out.write("\r\n");
      out.write("						$(\".botao-detalhes\").click(function() {\r\n");
      out.write("							var url = $(this).attr(\"data-url\");\r\n");
      out.write("							console.log(url);\r\n");
      out.write("							$.post(url, function(retorno) {\r\n");
      out.write("								$(\".modal-body\").html(retorno);\r\n");
      out.write("\r\n");
      out.write("							})\r\n");
      out.write("							$(\"#detalhes\").modal(\"show\");\r\n");
      out.write("						})\r\n");
      out.write("\r\n");
      out.write("						$(\".botao-deletar\")\r\n");
      out.write("								.click(\r\n");
      out.write("										function(event) {\r\n");
      out.write("											var id = $(this).attr('data-id');\r\n");
      out.write("\r\n");
      out.write("											var resultado = window\r\n");
      out.write("													.confirm(\"deseja excluir esse registro\");\r\n");
      out.write("											if (resultado == true) {\r\n");
      out.write("												window.location.href = \"configuracao.remover.logic?configuracao.id=\"\r\n");
      out.write("														+ id;\r\n");
      out.write("											}\r\n");
      out.write("										})\r\n");
      out.write("\r\n");
      out.write("					})\r\n");
      out.write("\r\n");
      out.write("	$(function() { /*LISTAGEM DA TABELA*/\r\n");
      out.write("\r\n");
      out.write("		$('#item1').dataTable({\r\n");
      out.write("			\"bPaginate\" : true,\r\n");
      out.write("			\"bLengthChange\" : true,\r\n");
      out.write("			\"lengthMenu\" : [ 50, 70, 100 ],\r\n");
      out.write("			\"bFilter\" : true,\r\n");
      out.write("			\"bSort\" : true,\r\n");
      out.write("			\"bInfo\" : true,\r\n");
      out.write("			\"bAutoWidth\" : false,\r\n");
      out.write("			order: [[1, 'asc']],\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$('#item2').dataTable({\r\n");
      out.write("			\"bPaginate\" : true,\r\n");
      out.write("			\"bLengthChange\" : true,\r\n");
      out.write("			\"lengthMenu\" : [ 50, 70, 100 ],\r\n");
      out.write("			\"bFilter\" : true,\r\n");
      out.write("			\"bSort\" : true,\r\n");
      out.write("			\"bInfo\" : true,\r\n");
      out.write("			\"bAutoWidth\" : false,\r\n");
      out.write("			order: [[1, 'asc']],\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
